services:
  - type: web
    name: WerkenBijSalm
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000
